#!/bin/sh
# Main system backups are carried out via ZFS send/receive,
# but that won't pick up /boot.
set -e

# ensure /boot is the real deal
mountpoint -q /boot || (echo "/boot is not a mountpoint" >&2; exit 1)

# bind mount / to a temporary path
fakeroot=$(mktemp -d)
mount --bind / $fakeroot

# copy the /boot filesystem into /'s boot/
rsync -a --delete /boot/ $fakeroot/boot/

# clean up
umount $fakeroot
rmdir $fakeroot
